version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: cah-postgres
    environment:
      POSTGRES_USER: cah_user
      POSTGRES_PASSWORD: CahStrongPass123
      POSTGRES_DB: chefathands
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
